import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  minify: prod,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();

  // 复制文件到 release 目录
  const releaseDir = "release";
  if (!existsSync(releaseDir)) {
    mkdirSync(releaseDir);
  }

  const files = ["main.js", "manifest.json", "styles.css"];
  for (const file of files) {
    if (existsSync(file)) {
      copyFileSync(file, `${releaseDir}/${file}`);
      console.log(`Copied ${file} to ${releaseDir}/`);
    }
  }

  process.exit(0);
} else {
  await context.watch();
}
